### PR TITLE
TypoClock Indonesian Language

### PR DESCRIPTION
**Pull request by 703joko**
For TypoClock. Indonesian language

### CODE REVIEW

**Comment by varund7726** [comment]
sorry its very poorly formatted. can you edit and format properly with tags on new lines? 
see other string resources. Thank you

**Comment by 703joko** [comment]
Sure..
Sorry for this carelessness, I didn't double check.I will fix it soon

Pada tanggal Sel, 8 Sep 2020 16.49, Varun Date <notifications@github.com>
menulis:

**Comment by 703joko** [comment]
Hope this is confirmed

**Comment by 703joko** [comment]
Thanks

Pada tanggal Sel, 8 Sep 2020 18.53, Varun Date <notifications@github.com>
menulis:

**Pull request merged**
