### PR TITLE
Arrays should be in one place - Notification stream title

### PR DESCRIPTION
**Pull request by ashoksoni**
This will also fix issues for disappearing Notification title in few cases where user flash rom along with several other zips. I haven't able to figure out the exact issue but this is the best solution I find and working for me.

Change-Id: I39a8f5880f20462007f032b81d43273f1e1a2f88

### CODE REVIEW

**Review by varund7726 — COMMENTED** [review]
This will create conflicts with aosp

**Comment by akhilnarang** [comment]
Yep please don't move aosp strings/arrays around

**Review by akhilnarang — COMMENTED** [review]
Yep please don't move AOSP Strings/Arrays around

**Comment by varund7726** [comment]
A clean flash will solve everything .thanks

**Comment by ashoksoni** [comment]
Sorry, didn't know it'll mess up things in future. Pretty new in all this. Thanks for the info.

**Comment by varund7726** [comment]
no problem :)

**Pull request closed without merging**
