### PR TITLE
Change of translation

### PR DESCRIPTION
**Pull request by Henry2o1o**
That is, in every ROM documents.
Is also the DocumentsUI.

### CODE REVIEW

**Comment by akhilnarang** [comment]
Crowdin.net/project/resurrectionremix

**Comment by Henry2o1o** [comment]
I have no authorization for this.

**Comment by Henry2o1o** [comment]
`<string name="app_label" msgid="xxxxxxxxxxxxxxxx">"Documents"</string>`
in german
` <string name="app_label" msgid="xxxxxxxxxxxxxxxx">"Dokumente"</string>`

**Comment by akhilnarang** [comment]
Change it on crowdin, it'll be pulled from there

**Comment by Henry2o1o** [comment]
ok :-)

**Comment by Henry2o1o** [comment]
http://Crowdin.net/project/resurrectionremix

Sorry, where is the dockumentui?

platform_frameworks_base/packages/DocumentsUI/res/values-de/strings.xml
platform_frameworks_base/packages/DocumentsUI/res/values/strings.xml

https://github.com/android/platform_frameworks_base/blob/master/packages/DocumentsUI/res/values/strings.xml

platform_frameworks_base/packages/DocumentsUI/res/values-en-rGB/strings.xml
<string name="app_label" msgid="2783841764617238354">"Documents"</string>

**Comment by akhilnarang** [comment]
OK sorry, that is part of AOSP Strings not RR strings.

Will merge here

**Pull request merged**
