### PR TITLE
Remove duplicate

### PR DESCRIPTION
**Pull request by boswelja**

### CODE REVIEW

**Comment by varund7726** [comment]
What duplicate?

**Comment by boswelja** [comment]
Further up in the file theres already an import for Uri

**Comment by varund7726** [comment]
Umm I see only one if there were Two build wouldve failed

**Comment by boswelja** [comment]
The following was taken directly from the marshmallow branch with the duplicates in bold:

import android.graphics.drawable.Drawable; 
import android.inputmethodservice.InputMethodService; 
**import android.net.Uri;**
import android.media.AudioAttributes; 
import android.media.MediaMetadata; 
import android.media.session.MediaController; 
import android.media.session.MediaSession; 
import android.media.session.MediaSessionManager; 
import android.media.session.PlaybackState; 
**import android.net.Uri;**
import android.os.AsyncTask; 
import android.os.Bundle;

**Comment by varund7726** [comment]
My bad .

**Pull request merged**
