### PR TITLE
DNM readme

### PR DESCRIPTION
**Pull request by fgl27**
Do not merge this as it has conflicts...

A few featuring are not fully working on RR, like hw keys don't light up and some etc random...

There is a lot of changes on LOS repos that are today old and they were not merge use this as sample of what is missing.

Please revise the changes that can be merged.

the pull log:

Changes to be committed:

	modified:   core/java/android/content/pm/PackageInfo.java
	modified:   core/java/android/content/pm/PackageParser.java
	modified:   core/java/android/os/PowerManager.java
	modified:   core/java/android/os/PowerManagerInternal.java
	modified:   core/java/android/util/NtpTrustedTime.java
	modified:   core/java/android/view/WindowManagerPolicy.java
	modified:   core/java/com/android/internal/statusbar/IStatusBar.aidl
	modified:   packages/SettingsProvider/AndroidManifest.xml
	new file:   packages/SettingsProvider/res/mipmap-anydpi/ic_launcher.xml
	new file:   packages/SettingsProvider/res/mipmap-hdpi/ic_background.png
	new file:   packages/SettingsProvider/res/mipmap-hdpi/ic_foreground.png
	deleted:    packages/SettingsProvider/res/mipmap-hdpi/ic_launcher_settings.png
	new file:   packages/SettingsProvider/res/mipmap-mdpi/ic_background.png
	new file:   packages/SettingsProvider/res/mipmap-mdpi/ic_foreground.png
	deleted:    packages/SettingsProvider/res/mipmap-mdpi/ic_launcher_settings.png
	new file:   packages/SettingsProvider/res/mipmap-xhdpi/ic_background.png
	new file:   packages/SettingsProvider/res/mipmap-xhdpi/ic_foreground.png
	deleted:    packages/SettingsProvider/res/mipmap-xhdpi/ic_launcher_settings.png
	new file:   packages/SettingsProvider/res/mipmap-xxhdpi/ic_background.png
	new file:   packages/SettingsProvider/res/mipmap-xxhdpi/ic_foreground.png
	deleted:    packages/SettingsProvider/res/mipmap-xxhdpi/ic_launcher_settings.png
	new file:   packages/SettingsProvider/res/mipmap-xxxhdpi/ic_background.png
	new file:   packages/SettingsProvider/res/mipmap-xxxhdpi/ic_foreground.png
	deleted:    packages/SettingsProvider/res/mipmap-xxxhdpi/ic_launcher_settings.png
	new file:   packages/SystemUI/res/drawable/ic_lock_airplane_mode_disabled.xml
	new file:   packages/SystemUI/res/drawable/ic_lock_airplane_mode_enabled.xml
	new file:   packages/SystemUI/res/drawable/ic_lock_restart_bootloader.xml
	new file:   packages/SystemUI/res/drawable/ic_lock_restart_recovery.xml
	new file:   packages/SystemUI/res/drawable/ic_lock_screenshot.xml
	new file:   packages/SystemUI/res/drawable/ic_lock_user.xml
	modified:   packages/SystemUI/res/values-ru/strings.xml
	new file:   packages/SystemUI/res/values/lineage_dimens.xml
	modified:   packages/SystemUI/src/com/android/systemui/globalactions/GlobalActionsComponent.java
	modified:   packages/SystemUI/src/com/android/systemui/keyguard/KeyguardViewMediator.java
	new file:   packages/SystemUI/src/com/android/systemui/statusbar/LineageStatusBarItemHolder.java
	modified:   services/core/java/com/android/server/audio/AudioService.java
	modified:   services/core/java/com/android/server/display/DisplayPowerController.java
	modified:   services/core/java/com/android/server/om/OverlayManagerService.java
	modified:   services/core/java/com/android/server/om/OverlayManagerServiceImpl.java
	modified:   services/core/java/com/android/server/statusbar/StatusBarManagerInternal.java
	modified:   services/core/java/com/android/server/statusbar/StatusBarManagerService.java
	modified:   services/core/java/com/android/server/wm/RootWindowContainer.java
	modified:   services/core/java/com/android/server/wm/WindowManagerService.java
	modified:   services/core/jni/com_android_server_input_InputManagerService.cpp
	modified:   services/core/jni/com_android_server_power_PowerManagerService.cpp
	modified:   services/core/jni/com_android_server_power_PowerManagerService.h

Unmerged paths:
  (use "git add <file>..." to mark resolution)

	both added:      core/java/android/app/NotificationGroup.aidl
	both modified:   core/java/android/os/IPowerManager.aidl
	both modified:   core/java/android/provider/Settings.java
	both modified:   core/java/android/view/IWindowManager.aidl
	both modified:   core/java/android/view/WindowManager.java
	both modified:   core/java/com/android/internal/statusbar/IStatusBarService.aidl
	both modified:   core/java/com/android/internal/widget/LockPatternUtils.java
	both added:      core/res/res/values/cm_strings.xml
	both added:      core/res/res/values/lineage_config.xml
	both added:      core/res/res/values/lineage_symbols.xml
	both modified:   packages/SystemUI/Android.mk
	both modified:   packages/SystemUI/plugin/src/com/android/systemui/plugins/GlobalActions.java
	both added:      packages/SystemUI/res/drawable/ic_qs_location_battery_saving.xml
	both modified:   packages/SystemUI/res/layout/quick_settings_brightness_dialog.xml
	both modified:   packages/SystemUI/res/layout/recent_apps.xml
	both modified:   packages/SystemUI/res/layout/status_bar.xml
	both added:      packages/SystemUI/res/values/cm_strings.xml
	both modified:   packages/SystemUI/res/values/config.xml
	both added:      packages/SystemUI/res/xml/status_bar_prefs.xml
	both modified:   packages/SystemUI/src/com/android/keyguard/KeyguardPINView.java
	both modified:   packages/SystemUI/src/com/android/systemui/globalactions/GlobalActionsDialog.java
	both modified:   packages/SystemUI/src/com/android/systemui/globalactions/GlobalActionsImpl.java
	both modified:   packages/SystemUI/src/com/android/systemui/qs/QSPanel.java
	both modified:   packages/SystemUI/src/com/android/systemui/qs/customize/TileAdapter.java
	both modified:   packages/SystemUI/src/com/android/systemui/qs/tileimpl/QSFactoryImpl.java
	both added:      packages/SystemUI/src/com/android/systemui/qs/tiles/LiveDisplayTile.java
	both modified:   packages/SystemUI/src/com/android/systemui/recents/views/TaskViewHeader.java
	both modified:   packages/SystemUI/src/com/android/systemui/screenshot/GlobalScreenshot.java
	both modified:   packages/SystemUI/src/com/android/systemui/settings/BrightnessController.java
	both modified:   packages/SystemUI/src/com/android/systemui/statusbar/CommandQueue.java
	both modified:   packages/SystemUI/src/com/android/systemui/statusbar/phone/NavigationBarFragment.java
	both modified:   packages/SystemUI/src/com/android/systemui/statusbar/phone/NavigationBarView.java
	both modified:   packages/SystemUI/src/com/android/systemui/statusbar/phone/NotificationPanelView.java
	both modified:   packages/SystemUI/src/com/android/systemui/statusbar/phone/PhoneStatusBarTransitions.java
	both modified:   packages/SystemUI/src/com/android/systemui/statusbar/phone/StatusBar.java
	both modified:   packages/SystemUI/src/com/android/systemui/statusbar/phone/StatusBarWindowView.java
	both modified:   services/core/java/com/android/server/BatteryService.java
	both modified:   services/core/java/com/android/server/policy/PhoneWindowManager.java
	both modified:   services/core/java/com/android/server/power/PowerManagerService.java
	both modified:   services/core/java/com/android/server/power/ShutdownThread.java

### CODE REVIEW

**Comment by Jaiglissechef-i9100** [comment]
Hum I'll do it for any packages because the compil is a bit unstable thx

**Comment by varund7726** [comment]
We can't merge this as los had force pushed their branches .hardware keys issue is present because you don't have the bool in device tree config . check out our device trees to solve your issues as we aren't tracking any hw keys stuff from los . also I don't see any other issue or feature from los not working

**Comment by SlyFox718** [comment]
I found a bug. it consists in that when you try to change the number of tiles in the quick settings in the orientation "portrait" the system breaks down.

**Comment by Jaiglissechef-i9100** [comment]
I have a bool in local for HWKeys.

U dont need this ??? : https://github.com/LineageOS/android_frameworks_base/commit/3fdb2b088ca7c531ad6e272bfebf69805d6a85bb

After merge this : https://github.com/LineageOS/android_frameworks_native/commit/6e58bf095e4f6d5e5123d2f90ea6f2737b6250d3

I have this error 

frameworks/base/services/core/jni/com_android_server_input_InputManagerService.cpp:255:18: error: 'android::NativeInputManager::pokeUserActivity' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    virtual void pokeUserActivity(nsecs_t eventTime, int32_t eventType);

frameworks/base/services/core/jni/com_android_server_input_InputManagerService.cpp:1261:34: error: allocating an object of abstract class type 'android::NativeInputManager'

**Comment by varund7726** [comment]
We are tracking our own fw native .how are you tracking lineage one

**Comment by varund7726** [comment]
And no we don't need it

**Comment by Jaiglissechef-i9100** [comment]
My bad, i'm still on Native LineageOS, I will update the manifest. Thanks for help 👍

**Pull request closed without merging**
