### PR TITLE
TorchService: add sysfs handling

### PR DESCRIPTION
**Pull request by nilac8991**

### CODE REVIEW

**Comment by varund7726** [comment]
any particular reason why we need this??

**Comment by nilac8991** [comment]
The commit is intended most of it for the msm7x30 based devices which finally allows Torch and flashled functions

**Comment by nilac8991** [comment]
It is fully tested by me so it should'nt cause any problem for the other devices

**Comment by varund7726** [comment]
Great .lets review it

**Comment by westcripp** [comment]
thanks. lets test it

**Pull request merged**
