### PR TITLE
Update always on back config

### PR DESCRIPTION
**Pull request by AndropaX**

### CODE REVIEW

**Review by varund7726 — COMMENTED** [review]
You can't put AND condition there .it will break other devices .

**Comment by AndropaX** [comment]
Are you sure ? I tested both with true and false and it works as should.

**Comment by varund7726** [comment]
OK I'll test again and get back you

**Comment by westcripp** [comment]
yeah guys need test before merge . we already changed tons of code about the hardware keys rebinding  stuff

**Comment by AndropaX** [comment]
Now i see that it affects longpress...
Keycode and repeatcount should be separated ?

**Pull request closed without merging**
