### PR TITLE
Comment Duplicated String

### PR DESCRIPTION
**Pull request by kutlay1653**
It gives build error : https://del.dog/mepesuxone.txt

### CODE REVIEW

**Comment by Hasaber8** [comment]
> It gives build error : https://del.dog/mepesuxone.txt

Del.dog is down, re paste the error somewhere else and send.

**Comment by kutlay1653** [comment]
```
frameworks/base/core/java/android/os/Build.java:74: error: duplicate declaration of field: DATE
```

**Comment by kutlay1653** [comment]
I don't have full log now . I only have this

**Comment by Hasaber8** [comment]
Ok the pr seems fine, fixes the error, but there must be a proper commit for it.

**Comment by Hasaber8** [comment]
Please close your PR , commit which derped it has been fixed and soon the source will be usable

**Comment by kutlay1653** [comment]
no problem Thanks for fixing

**Pull request closed without merging**
