### PR TITLE
Don't ignore back button with capacitive buttons disabled

### PR DESCRIPTION
**Pull request by AndropaX**
Xiaomi mi 4c has unique feature - double tap edge to go back 
https://www.youtube.com/watch?v=1jZ-XlFIX9s
This needs that to work both with disabled hw keys.

### CODE REVIEW

**Comment by varund7726** [comment]
does it break other devices?

**Comment by AndropaX** [comment]
Shouldn't, cmhw keydisabler already do the job. On cm this don't need any changes to work.

**Comment by fgl27** [comment]
I don't really like have back button enable, my device don't need I believed others don't too, if all keys are disable way keep one key because one device?

I'm not saying this must be revert but...
Can a special overlay bool (keep back always on) or a device check be implemented here??

After all there is only one device with this problem or there is more?

**Comment by AndropaX** [comment]
Device should use kernel node for key disabling. Your don't have that because it has visible button without backlight and shouldn’t use that as cm reference.

**Comment by fgl27** [comment]
this works very well for me and I have no idea how to enable cmhw in the kernel, now that this here is already implemented and works to every one, way I need to worry about find the specific key in the kernel that will allow me to implement the cmhw to this.

I will make a "bool" you can overlay in DT and keep back key always on, is way more smart.

**Comment by fgl27** [comment]
@AndropaX 

What you think?
https://github.com/bhb27/android_frameworks_base/commit/454c385cacf7ecc2b6617c97dad99b3a3defa399

Will test it know, seems ok to me.

**Comment by AndropaX** [comment]
Ok, I'll test and report back.

**Comment by AndropaX** [comment]
```
ERROR: /home/andropax/RR/frameworks/base/services/core/java/com/android/server/policy/PhoneWindowManager.java:4112: The method getResources() is undefined for the type PhoneWindowManager
ERROR: /home/andropax/RR/frameworks/base/services/core/java/com/android/server/policy/PhoneWindowManager.java:6671: The method getResources() is undefined for the type PhoneWindowManager
```

**Comment by fgl27** [comment]
your machine seems to build way more fast then my...

after I fix, will rebase the commit and let you know.

**Comment by fgl27** [comment]
I rebase it above.
@AndropaX

I test without setting the bool to true in DT and the back is disable just fine...

Can you set it to true and let me know if you can use the backbutton?

thanks.

**Comment by AndropaX** [comment]
Ok, i'll test this afternoon.

**Comment by AndropaX** [comment]
Ok, seems to be working.

**Comment by fgl27** [comment]
:+1:

**Comment by varund7726** [comment]
guys im implementing a new hw keys adaptation for N.. will let you know how it goes

**Comment by AndropaX** [comment]
New adaptation restores problem, this time without possibility of fix, as it doesn't use hw disabling at all. It just ignore buttons signal and set backlight to 0. It's much worse option than disabling buttons via kernel.

**Pull request merged**
