### PR TITLE
Charging indicators for text-only battery view

### PR DESCRIPTION
**Pull request by bdogg718k**

### CODE REVIEW

**Comment by akhilnarang** [comment]
@bdogg718k  did you test this

**Comment by bdogg718k** [comment]
Yep http://s24.postimg.org/46xn0vfpx/Screenshot_2015_07_05_10_47_26.png talking to Altan bout it now.

**Comment by akhilnarang** [comment]
there are conflicts

**Comment by bdogg718k** [comment]
lol..i know. it was my fault..fixing now

**Comment by akhilnarang** [comment]
okkk
if it works then merge :)
don't make a pull next time, test, if it works, push

**Comment by bdogg718k** [comment]
k

**Pull request closed without merging**
