### PR TITLE
Screen pinning improvements

### PR DESCRIPTION
**Pull request by bdogg718k**
Inspired by the way ASUS implemented their screen pinning, I took it upon myself to do the
same with our ROM and move the pinning icon next to the icon for dismissing a recent app.
- Matched the behavior of the recent dismiss icon
- Changes icon to dark if recent app uses a light primary color

See images to see the differences

AOSP/DU - http://i.imgur.com/DYoKmNL.png
ASUS Zenfone 2 (inspiration) - http://i.imgur.com/BybyGHp.jpg

What it looks like with this commit - http://i.imgur.com/33zJK0c.png

Change-Id: Ie3e160647ba90b99fd0e130abc79fb63ed0ad3f5

Works as advertised on RR. Dont know if u guys wanna put it in or not.

### CODE REVIEW

**Comment by westcripp** [comment]
Can you contact with me on hangouts?

**Comment by bdogg718k** [comment]
Yep

**Comment by BoredOutOfMyGit** [comment]
Hey @bdogg718k @westcripp this commit is outdated and has a bug in it where the icon will stay enabled even when disabled in settings

I since fixed that and added a vector and is much nicer :-)
http://gerrit.dirtyunicorns.com/#/c/16768/

**Comment by akhilnarang** [comment]
Thanks, will implement

**Pull request merged**
