### PR TITLE
Null ref causes system UI crash on orientation change.

### PR DESCRIPTION
**Pull request by MikeyNick**
Revert "Revert Themes: Check if newTheme has null fonts, icons, or overlays"

This reverts commit f3cecca28f7a83abe0028d15fbb02bc53e722df7.

### CODE REVIEW

**Comment by MikeyNick** [comment]
The build just finished, I'm uploading now and will let you know in 30 min or so, but I should think so :)

**Comment by westcripp** [comment]
yeah i made atest build to for d855 now uploading.we ll see

**Comment by westcripp** [comment]
ok let me know if it works

**Comment by MikeyNick** [comment]
Worked for me on moto ghost, I can now go landscape without SystemUI force closing

**Comment by westcripp** [comment]
ok thanks for confirmation

**Pull request merged**
