### PR TITLE
Restore multi-sim colors

### PR DESCRIPTION
**Pull request by AndropaX**
This is used to assign color to sim card and it shouldn't be one color.

### CODE REVIEW

**Comment by varund7726** [comment]
@westcripp

**Comment by westcripp** [comment]
@AndropaX  ok good . can you change teal 700 with this #536DFE and teal 800 : #5C6BC0 . its depreciated color on rr m

**Comment by westcripp** [comment]
or anyways . its meged

**Comment by AndropaX** [comment]
But it's one problem, that colors are named in sim management settings and that would need change it in all languages

**Comment by westcripp** [comment]
yeah i forgot it . so i have no m sim device and no this option ..lol .i thought it generates itself automatically

**Pull request merged**
