### PR TITLE
base: set default animation scaling to 0.5

### PR DESCRIPTION
**Pull request by fgl27**
Signed-off-by: Felipe Leon <fglfgl27@gmail.com>

### CODE REVIEW

**Comment by fgl27** [comment]
are you guys shore 1x is so slow?

**Comment by westcripp** [comment]
this is very dirty way to do this . and animations are not slow as m anymore

**Comment by varund7726** [comment]
No need for this .animations can be dynamically adjusted

**Comment by fgl27** [comment]
Ok guys I use locally this, default 1x is too slow to me, maybe in others device it is not. and this is the default location for this configuration so I don't understand the dirty part.

:+1:

**Comment by westcripp** [comment]
@bhb27   firstly this is the original base commit https://github.com/ResurrectionRemix/android_frameworks_base/commit/711582b1ccb6f8425b66346b7aece7dca575d595

second : do not forget the settings part https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/commit/7f09c7175a9e7598bb5cea8fc0a87a4546ff0615

and 0.50 is too fast

**Comment by westcripp** [comment]
@bhb27 If you are maintaining any device . pls keep the stock animation values . because no one wont like very fast animations as default . and pls keep the source same as ours  . this is the maintaining rules . **Thanks**

**Comment by fgl27** [comment]
I understand, thanks you.

**Comment by ZeNiXxX** [comment]
Good!  0.5 is the best animationspeed thx

**Comment by fgl27** [comment]
just as reference in case some one wanna use this in the future, the arrays was move to base some time ago and 0.5 is in there that is way I push this as I test the default is change to .5 and I see improves...

https://github.com/ResurrectionRemix/android_frameworks_base/blob/nougat/packages/SettingsLib/res/values/arrays.xml#L168

again maybe only on my device but I really like it.

:+1:

**Pull request closed without merging**
