### PR TITLE
Nougat oms

### PR DESCRIPTION
**Pull request by Eliminater**

### CODE REVIEW

**Comment by varund7726** [comment]
. And pls take down your oms builds on xda. we are not publishing oms builds

**Comment by AdmireTheDistance** [comment]
How is favoring CMTE over OMS being "fair" to themers? OMS is becoming more widely used and favored every day, and has far better support. If anything, you're being unfair to themers by only using CMTE (and by being total dicks to those that make unofficial OMS builds).

**Comment by varund7726** [comment]
Yeah exactly my point? And who the hell are you? 
Whatever 
Once cmte comes out , well have to revert all oms patches .so what then? What about the users who paid for oms themes? @admirethedistance 
. 
RR is our damn ROM .who the hell gives you the right to tell is what to do? And what you make us do? Our source our rules so stfu

**Comment by Eliminater** [comment]
Can we continue to build and distribute builds with your base when we remove oms?

**Comment by akhilnarang** [comment]
@Eliminater if the device already has an official build, then please do not make unofficial threads

**Comment by ghost** [comment]
@akhilnarang

Why?  I just don't get it.  I'm a member for years on xda and there were always unofficial or optimized builds and threads of several roms?  What happened ? You know that with such thinking the xda development site will be dead in short time. All the rom developers are "alive " cause of the xda community or the people who are you using. I'm totally sure that for example rr closes there sources... There going to loose such a massive user support. That will be the end for them and it will be their would. And the People who made unofficial builds or made an xda thread, they write that it isn't their rom and who are the real devs...  I don't get it what the problem is...  You will destroy the meaning of open source and xda....  Or is money the key?  But with this and without the community rr will die to...  As all other roms.

**Comment by varund7726** [comment]
@ViktorHermann users like whom? Like @Blackjubel ? He's the biggest kanger I have ever come across .and no RR community will NOT die just because we stop unofficial threads .there's no connection .if other ROMs want to use our work , then can use git cherry-pick and use our commits .no worries .but why the hell do people like @Blackjubel want to use our ROM as base all the time .and FYI official builds are call official for a reason .because they are stabler than the rest . I have examples of many people who just compile ROMs from source , post threads on XDA and all they want is thanks , fame and donation.basically making money of our hard work taking credit for it .that's why

**Comment by BlackDeaths** [comment]
Lol therefore the users love my Rom´s rather and are more stable than the official klte !!!!!
And I did not need to donate to make it out for fun !!!!!
They are like a small child @varund7726 !!!!!!


open source They do not know it's called duden is supposed to help !!!!!!!

The little small money can have RR who you are only about the money goes !!!!!!!!

**Comment by varund7726** [comment]
@Blackjubel  first of all speak clearly and stop using google translate
Nobody loves your rom coz you havent done anything to modify it anyways
you dont even know how to use git cherry-pick or git push
and hold on .who said its **YOUR** rom? do you know everybody on xda doesnt want you around just because of your kangs?
who gives you permission for all this anyways?
why do you use our rom man? why use our hard work? why dont you start something of your own and call it **your OWN** rom. instead of stealing others work and calling it your own

**Comment by westcripp** [comment]
@Blackjubel I just want to know that . did you ask permission about the rebase and re optimise the rr source and make it your own ? and you are disrespecting to developers work . most of your commits informing wrong authorship. thats the main point we cant let it go . if you wanna make a rom based on rr source . you have to ask permission first . i dont remember that we allow you to do this . open source is not means you can kang what every you want

**Pull request closed without merging**
