### PR TITLE
Added missing Greek tranlations for framework

### PR DESCRIPTION
**Pull request by CrisBalGreece**
Please check and add these Greek tranlations

### CODE REVIEW

**Review by varund7726 — COMMENTED** [review]
@akhilnarang is it ok to edit this file for translation?

**Comment by CrisBalGreece** [comment]
Hey..Of course..Why not.
What's the problem?
Thanks for your reply..

**Comment by CrisBalGreece** [comment]
Just for info..
I've compiled RR-OS Unofficial for LeEco LeMax2 (x2) successfully with these additions.
Everything working..
Thanks again for your time and replies.

**Comment by varund7726** [comment]
Ok then merged

**Comment by CrisBalGreece** [comment]
Thanks allot.
Keep moving and take care my friend..
Great job..RR is back..

**Pull request merged**
