### PR TITLE
Wifi AP Disabled from Subscription chang

### PR DESCRIPTION
**Pull request by knone1**
fix build

### CODE REVIEW

**Comment by ShevT** [comment]
+1
Because of this upgrade: https://github.com/CyanogenMod/android_frameworks_opt_net_wifi/commit/5a4704de82e9f1f49c575dcae6e7bde0637ab2a1 we get an error during assembly

**Comment by knone1** [comment]
yes :)

**Comment by varund7726** [comment]
DO NOT merge pull requests without authorship

we will run into issues ahead

this commit belongs to https://github.com/CyanogenMod/android_frameworks_base/commit/a5979d69527d384d360574ecdec8b73f5fc9ec33
not you!

wait im uploading changes and fixing build

**Comment by knone1** [comment]
yes no problem

**Pull request closed without merging**
