### PR TITLE
SystemUI: Add back option to set color for statusbar clock [2/2]

### PR DESCRIPTION
**Pull request by mobspyguy**
References
https://github.com/ResurrectionRemix/android_frameworks_base/commit/0323a4db0a34bdfb2a90c0cf6fccb4f0002e5f25
https://github.com/temasek/android_frameworks_base/commit/3eee47fd171042ac98eb58717ac0b935e4198218

### CODE REVIEW

**Comment by mobspyguy** [comment]
Change author

**Comment by varund7726** [comment]
Does the icon go dark on light SB  backgrounds? That is important

**Comment by mobspyguy** [comment]
Ok, then I will check this next days and create a pull request after test with correct author.

**Comment by varund7726** [comment]
OK 👍

**Comment by mobspyguy** [comment]
@varund7726 
Please look at StatusBarIconController.java line 672 and you will see that clock color is SB background dependent. By the way this works only if default color (white) is set. For example I changed the brand logo color to orange, then neither on light nor dark status bar background color changes the brand logo color. 

Perhaps you have also a solutions for this situation: If I activate energy safe mode the status bar background color goes to orange. If I set brand logo color or clock color to orange, then both not visible.

**Comment by varund7726** [comment]
Its breaking some themes as of now .so you can merge this in your personal builds if you need . closing this as of now
Good day

**Pull request closed without merging**
