### PR TITLE
Fix homekey wake device

### PR DESCRIPTION
**Pull request by aminfauzi**

### CODE REVIEW

**Comment by varund7726** [comment]
Tested?

**Comment by aminfauzi** [comment]
> 
> 
> Tested?

Yes. it working. im able to wake device using home key while screen off.

**Comment by varund7726** [comment]
No but im saying ths solution is not correct .you must add this overlay in your device tree config_deviceHardwareWakeKeys

For more info check readme https://github.com/ResurrectionRemix/platform_manifest

**Comment by aminfauzi** [comment]
> 
> 
> No but im saying ths solution is not correct .you must add this overlay in your device tree config_deviceHardwareWakeKeys
> 
> For more info check readme https://github.com/ResurrectionRemix/platform_manifest

yes the overlay added. but hw key still not working because it disable in coding. so the commit enable it back.

**Comment by varund7726** [comment]
when switch of waking keys is off it does it still wake?

**Comment by varund7726** [comment]
Also what about other wake keys?

**Comment by aminfauzi** [comment]
> 
> 
> when switch of waking keys is off it does it still wake?

nope. wake key working properly with this commit.

**Comment by varund7726** [comment]
ok last thing . have you tested other wake keys? menu and back keys

**Comment by aminfauzi** [comment]
> 
> 
> ok last thing . have you tested other wake keys? menu and back keys

yes. other capacitive button works fine here.  do you have telegram? easier for me to show to you.

**Comment by varund7726** [comment]
@varund7726 telegram

**Comment by varund7726** [comment]
Merged separately

**Pull request closed without merging**
