### PR TITLE
Update to latest tag r37

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by akhilnarang** [comment]
Cool

**Comment by ghost** [comment]
;)

**Comment by akhilnarang** [comment]
@ishantvivek RR LP builds fine now?

**Comment by ghost** [comment]
Build going on,but i don't think anything going to broke,still i will update you after build is completed

**Comment by akhilnarang** [comment]
Cool :+1:

**Comment by ghost** [comment]
@akhilnarang where does part 2 of this [commit](https://github.com/ResurrectionRemix/android_frameworks_base/commit/acd9545f81b5723a2632cab139a1bee88e5c6999) lie?
Getting error every time 
Error:-frameworks/base/packages/SystemUI/src/com/android/systemui/qs/tiles/MusicTile.java:208: error: method does not override or implement a method from a supertype
        @Override
        ^
frameworks/base/packages/SystemUI/src/com/android/systemui/qs/tiles/MusicTile.java:211: error: method does not override or implement a method from a supertype
        @Override
        ^

**Comment by akhilnarang** [comment]
Settings

**Comment by ghost** [comment]
Settings is tracked from rr branch,so things should work fine, but it's not,getting error everytime,also none of the new commit is linked to it.😮

**Comment by ghost** [comment]
@varund7726 pls look into the issue?

**Comment by varund7726** [comment]
just remove override from the lines given and it should be fine

**Comment by ghost** [comment]
No need, i reverted this commit and things go fine.
edc3958f

**Comment by Jprimero15** [comment]
😂😂😂

**Pull request merged**
