### PR TITLE
Update Italian translation

### PR DESCRIPTION
**Pull request by entony80**

### CODE REVIEW

**Comment by akhilnarang** [comment]
https://crowdin.com/project/resurrectionremix
@entony80 please submit there
Thanks :)

**Comment by entony80** [comment]
Great did not know of Crowdin
Thanks ;)

**Comment by lindwurm** [comment]
@akhilnarang please allow us to download files from Crowdin. 
I want to test build on local environment

[screenshot 2745_](https://crowdin.com/translate/resurrectionremix/30/en-ja)
[screenshot 2746_](https://crowdin.com/translate/cyanogenmod/3620/en-ja)

**Comment by akhilnarang** [comment]
Will check it out

**Comment by akhilnarang** [comment]
Done @lindwurm

**Comment by lindwurm** [comment]
thanks :) @akhilnarang

**Comment by akhilnarang** [comment]
=)

**Pull request closed without merging**
