### PR TITLE
Navbar on/off and custom dimensions (1/2)

### PR DESCRIPTION
**Pull request by Compunctus**
Please tell me if i forgot anything.

Forward port from lollipop5.1
Look for second commit in packages/apps/Settings. Will push it shortly, want to polish it some more.

Authors:
@westcripp
@hany
Lokesh Chamane
@kufikugel
@cristianomatos
Authors of PAC and Slim roms

### CODE REVIEW

**Comment by hany** [comment]
Hey there folks, I think there's some mistake here. I am not an author here, and I believe credit is being given in error.

**Comment by varund7726** [comment]
@hany ok no Prob Ill Give the proper Authorships

**Comment by Compunctus** [comment]
commit a850093086410ec6c443003526b44a12403f9765
Author: hany hany.alsamman@gmail.com
Date:   Fri Jan 10 23:53:47 2014 +0000

```
Navigation bar dimensions and Master switch (1/2)

- Change height when in portrait
- Change width when in landscape
- Option to enable or disable nav bar

This is partially ported from SlimRoms
Thanks to @kufikugel
```

Was i mistaken in thinking that this commit was authored by you?..
Ah, i see. Same username, different user. Sorry.
Credit should go to @codex-corp

**Comment by varund7726** [comment]
ok @Compunctus ill fix this

**Comment by westcripp** [comment]
@varund7726  im also not Author of this commit

**Comment by Compunctus** [comment]
commit 77b04e1d5a49385c3a522b5862b3686905eda920
Author: westcripp korukaltan@gmail.com
Date:   Wed Jun 4 22:20:12 2014 +0300

```
Navigation bar dimensions (2/2)

- Change height when in portrait
- Change width when in landscape
- Option to enable or disable nav bar

additional options

- Ability to disable hardware keys via nav bar settings
- Add android:key in hardware keys enable/disable option to forward enable t
- Check devices related core/res/res/values/config.xml to enable or disable

credits to crdroid
```

Not this one, but you worked on that code. Several commits after are made by you, such as
commit c1c985a16ecad9a4635ac33427d9ba7ffb502010
Author: westcripp korukaltan@gmail.com
Date:   Mon Dec 15 04:30:02 2014 +0200

```
Base : Add navigation bar dimensions
credit Lokesh Chamane and pac rom
credit Lokesh Chamane and pac rom

Change-Id: If08f7fe07f3d6324a4684d58399a30e3617207b6
```

A lot of people have changed that code. It came a long way from being just a dynamic navbar implementation. I think listing everyone who worked on it would be good, no?

**Comment by varund7726** [comment]
authorship has been fixed
@westcripp  https://github.com/ResurrectionRemix/android_frameworks_base/commit/c416703be1683fc3b22a2df83de1fef815babf37

Please force pull base branch

**Pull request merged**
