### PR TITLE
Fix duplicate entries

### PR DESCRIPTION
**Pull request by boswelja**
There was 2 Settings imports, now theres one

### CODE REVIEW

**Comment by varund7726** [comment]
your commit message " Srsly, another dupe?" still has not been changed
Change it completely mate 
whats the point of that msg?

**Comment by boswelja** [comment]
I found a duplicate earlier, I wasnt expecting another one

**Comment by varund7726** [comment]
so? does that mean that the commit message should be  " Srsly, another dupe?" 
Its a very rude one as if your trying to troll someone

**Comment by boswelja** [comment]
Im sorry if you find it rude, but I dont see how it is rude at all

**Comment by westcripp** [comment]
we ll add these titles to changelogs . so we need readable titles

**Comment by boswelja** [comment]
Ok, I will take more time to write titles and descriptions :)

**Comment by westcripp** [comment]
thank you

**Pull request merged**
